# Python and NumPy revisited

In [1]:
import numpy as np

## Array creation

### Conversion from another python data structure

from list:

In [2]:
l = [1,2,3]
np.array(l)

array([1, 2, 3])

from tuple:

In [3]:
t = (6.05673, 52.56220)
np.array(t)

array([ 6.05673, 52.5622 ])

### Array generator functions

In [4]:
np.arange(6) 
# half-open interval [0, 6⟩
#  numpy.arange([start, ]stop, [step, ]dtype=None)

array([0, 1, 2, 3, 4, 5])

In [5]:
np.linspace(0, 1, 12) 
# closed interval with number of steps
# np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [6]:
np.zeros(10, dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones((2, 3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.full((4,2), 5) # Create a 4×2 array filled with 3.14


array([[5, 5],
       [5, 5],
       [5, 5],
       [5, 5]])

In [9]:
np.empty(20, dtype=np.int64)

array([25895968444448860, 33495917369360483, 32370081890697327,
       28429397855895664, 27303506540232796, 30962698416554083,
       27866516621623399, 32651569751457897, 27866473672605801,
       31244156213330015, 31525665550303331, 30962698417340533,
       13511013636702311, 12948244068892722, 25896204670730341,
       25896118771056748, 28429470870863987, 27866439313522733,
       28429415035764843, 32933044727578739], dtype=int64)

## Array attributes

In [10]:
np.random.seed(0) # seed for reproducibility

x1 = np.random.randint(5, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.rand(2,3,4)

In [11]:
x1

array([4, 0, 3, 3, 3, 1])

In [12]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [13]:
x3

array([[[0.47997717, 0.3927848 , 0.83607876, 0.33739616],
        [0.64817187, 0.36824154, 0.95715516, 0.14035078],
        [0.87008726, 0.47360805, 0.80091075, 0.52047748]],

       [[0.67887953, 0.72063265, 0.58201979, 0.53737323],
        [0.75861562, 0.10590761, 0.47360042, 0.18633234],
        [0.73691818, 0.21655035, 0.13521817, 0.32414101]]])

In [14]:
print("x1 ndim: ", x1.ndim)
print("x1 shape: ", x1.shape)
print("x1 size: ", x1.size)
print("x1 dtype", x1.dtype)
print()
print("x2 ndim: ", x2.ndim)
print("x2 shape: ", x2.shape)
print("x2 size: ", x2.size)
print("x2 dtype", x2.dtype)
print()
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)
print("x3 dtype", x3.dtype)

x1 ndim:  1
x1 shape:  (6,)
x1 size:  6
x1 dtype int32

x2 ndim:  2
x2 shape:  (3, 4)
x2 size:  12
x2 dtype int32

x3 ndim:  3
x3 shape:  (2, 3, 4)
x3 size:  24
x3 dtype float64


## Array indexing and slicing

### Indexing

In [15]:
arrA = np.arange(8)
arrA

array([0, 1, 2, 3, 4, 5, 6, 7])

In [16]:
arrA = arrA.reshape((2,4))
arrA

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [17]:
arrA[1,3] # no need to do [1][3]

7

In [18]:
arrA[1][3] # arrA[1][3] still works but is inefficient 

7

In [19]:
arrA[1] # no index for the second dimension! 

array([4, 5, 6, 7])

In [20]:
arrA[:,2]

array([2, 6])

In [21]:
arrA[:,1] = [10,12] # works as long as dimension is right
arrA

array([[ 0, 10,  2,  3],
       [ 4, 12,  6,  7]])

Use an integer array as index

In [22]:
arrA = np.arange(8, 1, -1)
arrA


array([8, 7, 6, 5, 4, 3, 2])

In [23]:
arrA[[2,3,2,4]]         

array([6, 5, 6, 4])

In [24]:
arrA[ np.array([[1,1],[2,3]]) ]  # result mimics the shape of the index array

array([[7, 7],
       [6, 5]])

Array indices in multiple dimensions

In [25]:
yourTwoDimArray = np.arange(30).reshape(5,6)
yourTwoDimArray

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [26]:
yourTwoDimArray[ np.array([0,2,3]), np.array([1,1,1]) ]

array([ 1, 13, 19])

In [27]:
yourTwoDimArray[ np.array([0,2,3]) ]

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

### Slicing

In [28]:
x = np.arange(10, 30)

Reverse array

In [29]:
x[::-1]

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

Every other element

In [30]:
x[::2]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [31]:
x = np.arange(0, 24).reshape((4,6))
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [32]:
x[:2,:3]

array([[0, 1, 2],
       [6, 7, 8]])

In [33]:
x[:,1] # Second column

array([ 1,  7, 13, 19])

In [34]:
x[2,:] # Third row

array([12, 13, 14, 15, 16, 17])

NumPy slicing returns view rather than copy

In [35]:
x_slice = x[0, 4:]
x_slice

array([4, 5])

In [36]:
x_slice[0] = 100
x_slice[1] = 200

In [37]:
x

array([[  0,   1,   2,   3, 100, 200],
       [  6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23]])

## Concatenation

In [38]:
x = np.array([4,5,6])
y = np.array([8,9,10])
np.concatenate([x, y])

array([ 4,  5,  6,  8,  9, 10])

In [39]:
z = np.array([[11,22,33],
              [99,88,77]])
z

array([[11, 22, 33],
       [99, 88, 77]])

In [40]:
np.concatenate([z, z]) # concatenate along the first axis

array([[11, 22, 33],
       [99, 88, 77],
       [11, 22, 33],
       [99, 88, 77]])

In [41]:
np.concatenate([z, z], axis = 1) # concatenate along the second axis

array([[11, 22, 33, 11, 22, 33],
       [99, 88, 77, 99, 88, 77]])

## UFuncs


In [42]:
x = [2., 3., 5., 12., 30.]

reciprocals = []
for e in x:
    reciprocals.append(1. / e)

print(reciprocals)

[0.5, 0.3333333333333333, 0.2, 0.08333333333333333, 0.03333333333333333]


In [43]:
x = np.array([2., 3., 5., 12., 30.], dtype=np.float)
reciprocals = 1. / x
print(reciprocals)

[0.5        0.33333333 0.2        0.08333333 0.03333333]


C:\Users\FARNAG~1\AppData\Local\Temp/ipykernel_23560/604273405.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array([2., 3., 5., 12., 30.], dtype=np.float)


In [44]:
x = np.arange(5)

print(.3 * x + x**2 + 12)

[12.  13.3 16.6 21.9 29.2]


## Aggregation

In [45]:
x = np.random.random(100)

In [46]:
np.sum(x)

53.54381896006251

In [47]:
x = np.arange(1, 16).reshape((5, 3))
print(x)
print("Sum of columns: ", x.sum(axis=0))
print("Sum of rows: ", x.sum(axis=1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
Sum of columns:  [35 40 45]
Sum of rows:  [ 6 15 24 33 42]


## Broadcasting

In [48]:
x = np.array([10, 20 , 30])
y = np.array([3, 2, 1])
print(x + y)

[13 22 31]


In [49]:
y = y.reshape((1, 3))
print(y)

[[3 2 1]]


In [50]:
print(x.reshape((3,1)) + y)

[[13 12 11]
 [23 22 21]
 [33 32 31]]


In [51]:
a = np.arange(3)
print(a)
print()
b = np.arange(3)[:, np.newaxis]
print(b)
print()
print(a + b)

[0 1 2]

[[0]
 [1]
 [2]]

[[0 1 2]
 [1 2 3]
 [2 3 4]]


## Comparisons and Boolean Logic

In [52]:
x = np.array([7, 8, 13, 80, 12, 1, 5])
print(x > 12)

[False False  True  True False False False]


In [53]:
x[x > 12]

array([13, 80])